name: kmeans-clustering
on: 
  - push
jobs:
  Kmeans:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name : "run KMeans"
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # the ML workflow goes here
          pip3 install -r requirements.txt
          python3 preprocess_data.py
          python3 model.py

          echo "##Elbow method graph" >> report.md
          echo "" The optimal number of clusters for k-means clustering is displayed below"
          cml-publish inertia.png --md >> report.md

          echo "##Kmeans graph" >> report.md
          echo "" The KMeans predictions are displayed below"
          cml-publish kmeans.png --md >> report.md

      
