name: kmeans-clustering
on: 
  - push
jobs:
  Kmeans:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:0-dvc2-base1-gpu
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name : "run KMeans"
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # the ML workflow goes here
          mkdir processed_data
          pip3 install -r requirements.txt
          python3 preprocess_data.py
          python3 model.py
          
          # Add plots to markdown
          echo "##Elbow method graph" >> report.md
          echo "" The optimal number of clusters for k-means clustering is displayed below" >> report.md
          echo "![Elbow graph](./inertia.png)">> report.md

          echo "##Kmeans graph" >> report.md
          echo "The KMeans predictions are displayed below" >> report.md
          echo "![Kmeans graph](./kmeans.png)" >> report.md
          
          # Create comment from markdown report
          cml comment create report.md

      
